### ISSUE TITLE
Licensing disambiguation

### ISSUE THREAD

**Issue by eclipseo** [agordon/Authen-ModAuthPubTkt#1]
@agordon 

Hi, I need to package your Perl script as a dependency for [Ravada](https://github.com/UPC/ravada), but I have conflicting information regarding the license:

 - The license from README and lib/Authen/ModAuthPubTkt.pm: "Apache License, same as the rest of mod_auth_pubtkt". That license <https://github.com/manuelkasper/mod_auth_pubtkt/blob/master/LICENSE> is "ASL 1.0".

 - The license from META.json and Makefile.PL: perl_5.

Could you please clarify which one applies? Is the license in Makefile.PL and META.json a mistake? Also could you replace "same as the rest of mod_auth_pubtkt" with an actual license name?

Moreover, the ASL 1.0 license requires a copy of the license provided with the sources, could you please add it to the package on MetaCPAN?

```
* 6. Redistributions of any form whatsoever must retain the following
*    acknowledgment:
*    "This product includes software developed by the Apache Group
*    for use in the Apache HTTP server project (http://www.apache.org/)."
```

Thank you.

**Comment by eclipseo** [comment]
@agordon Any chance you could take a quick look at this?

**Comment by agordon** [comment]
@eclipseo - it's now license "same as Perl itself".
Hope this resolves the matter. Please remember this is *ten* years old module, hasn't been updated or maintained. Use at your own risk.

**Comment by eclipseo** [comment]
Thank you.
